---
title: "Homework 5"
author: "Daniel Ojeranti"
date: "11/10/2020"
output: html_document
---

```{r, setup, echo = F, message = FALSE, warning=FALSE}
library(tidyverse)
library(p8105.datasets)
library(hexbin)
library(ggridges)
library(patchwork)
knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Problem 1

Read in data.

```{r}
homicide.df =
  read_csv("homi-data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city,state,sep = "-"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>% 
  select(city_state,resolved) %>% 
  filter(city_state != "Tulsa_AL")
  
```

```{r}
aggregate.df=
  homicide.df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate.df %>%  filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate.df %>%  filter(city_state == "Baltimore_MD") %>% pull(hom_total) %>% broom::tidy()


```

Try to iterate

```{r}
results.df =
  
  aggregate.df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```

```{r}
results.df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_states, y = estimate)) +
  geom_point() +
  geom_errorbar((aes(ymin = conf.low, tmax = conf.high)))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


ANOTHer Way Processing...


```{r}
city_prop_test = function(df){
  
  n_unsolved ...
  n_total ...
  
  prop.test(....)
}
homicide.df =
  read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city,state,sep = "-"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>% 
  select(city_state,resolved) %>% 
  filter(city_state != "Tulsa_AL")
  nest(data = resolved)
```

## Problem 2

Import data

```{r}
data.1 = read_csv("lda_data/con_01.csv")
```

```{r}
path_df =
  tibble(
    path = list.files("lda_data"),
  ) %>% 
  mutate(
    path = str_c("ida_data/", path),
    data = map(......))

read_csv(path_df$path[[1]])
    
```


